### ISSUE TITLE
Incompatible with python3 - CoinSpot API also down

### ISSUE THREAD

**Issue by bakersemail** [geekpete/py-coinspot-api#15]
Hi geekpete,

I tried converting the coinspot.py to python3 compatible:
- switching the httplib to requests
- signature:
-- encoding utf-8 for the secret
-- encoding utf-8 for json payload

but it always returns a {"status":"invalid"}. is there something else that needs to be done to make this python3 compatible?

Sample code:
```from time import time
import hashlib
import json
import hmac
import requests

def apiRequest(apiModel, method, apiKey, secret):
        postdata = {}
        nonce = int(time()*1000000)
        postdata['nonce'] = nonce
        sign = hmac.new(secret.encode('utf-8'), json.dumps(postdata).encode('utf-8'), hashlib.sha512).hexdigest()

        headers = {}
        headers['Content-type'] = 'application/json'
        headers['Accept'] = 'text/plain'
        headers['key'] = apiKey
        headers['sign'] = sign

        response = requests.post('https://www.coinbase.com.au/api/my/balances', headers=headers, data=json.dumps(postdata))
        return response.text
```

**Comment by davidobrien1985** [comment]
I think the whole API is broken on Coinspot's side.

I can't even get to authenticate using simple curl.

**Comment by geekpete** [comment]
Hey @bakersemail if you want to submit a PR then I'd be keen to take a look, thanks for your work on this!

@davidobrien1985 I've reached out to the Coinspot team around their possible API issues as well.

**Comment by geekpete** [comment]
Hey Team, the feedback is that there's currently some issues with the API at the coinspot end and they are aware of this and will work to fix it as soon as they can but cannot provide an ETA.

If I hear more, I'll let you know.

**Comment by davidobrien1985** [comment]
Yeah, I got the same response a week ago and never heard back from them again when asking a follow-up question.

**Comment by bakersemail** [comment]
I contacted CoinSpot and they acknowledged there's something wrong with their API at the moment. No ETA on the fix yet.

**Comment by bakersemail** [comment]
Updated the title of this to let others know quickly. Spent a good 4 hours bashing my head against the wall only to find out it's on CoinSpot's side.

**Comment by geekpete** [comment]
Thanks for that

**Comment by axsdenied** [comment]
Any idea if the API has been fixed yet?

**Comment by geekpete** [comment]
I've had no notification that it's back up yet. I've asked Coinspot to notify me or post a blog post once they have it operational again so users can be notified. I also suggested they might use a public status page for it for more transparent visibility of uptime.

**Comment by aspiringguru** [comment]
just tried the demo code from the git repo. https://github.com/geekpete/py-coinspot-api

from coinspot import CoinSpot
client = CoinSpot()

have set api key and secret in environment variables.

getting 
{"status":"invalid"} 

if I set the api key and secret to invalid values, the test script hangs.
if I delete the environment variables COINSPOT_API_KEY & COINSPOT_API_SECRET the script returns {"status":"no key"}

so it seems the api problem is still on the coinspot side.

if anyone has a workaround pls link/post. 

oh and btw: thanks for creating this package.

**Comment by aspiringguru** [comment]
coinspot just responded, they are aware of the issue and working on it, but have no ETA for solution at moment.

**Comment by NickFi** [comment]
I asked Coinspot about API today (May 04, 2018) and I received a response within minutes:  
"CoinSpot appreciate that we need to support developers and the use of our API. 
Our Dev Team are aware of this and plan to update as soon as possible, however we can not provide an ETA at this stage. We apologise for the inconvenience."

**Comment by davidobrien1985** [comment]
@NickFi that is word for word the response I received 6 months ago...

**Comment by pv1991** [comment]
The following has worked for me in Python 3:

import configparser
import hashlib
import hmac
import json
import pprint
import requests
from time import time

def getCoinspotPrices(crypto):
    key = config['COINSPOT']['Key']
    secret = config['COINSPOT']['Secret'].encode('utf-8')
    nonce = int(time() * 1000000)
    postdata = {
                'nonce': nonce,
                'cointype': crypto
                }
    postdata = json.dumps(postdata, separators=(',', ':'))
    sign = hmac.new(secret, postdata.encode('utf-8'), hashlib.sha512).hexdigest()
    headers = {
                'Content-Type': 'application/json',
                'key': key,
                'sign': sign
               }

    r = requests.post('https://www.coinspot.com.au/api/orders', headers=headers, data=postdata)
    response = r.json()
    pprint.pprint(response)

**Comment by bakersemail** [comment]
@pv1991 If it's working with that code, I'm guessing CoinSpot have fixed their API. Should be okay to just close this.

**Comment by ggautama** [comment]
Any one willing to share a python 3 compatible version if they have it working... Not just snippets pretty please?

**Comment by xavierthompson** [comment]
> Any one willing to share a python 3 compatible version if they have it working... Not just snippets pretty please?


```
import os
import sys
import requests
import pandas as pd
import json
from time import time
import hmac
import hashlib
from itertools import count
import urllib.parse


api_key = 'yourapikeyhere'
api_secret_key = b'yoursecretkeyhere'
url = 'https://www.coinspot.com.au/api/ro/my/balances'

NONCE_COUNTER = count(int(time() * 1000))

payload = {
    'nonce' : next(NONCE_COUNTER)
}

payload = json.dumps(payload, separators=(',',':'))
signature = hmac.new(api_secret_key, payload.encode('utf-8'), digestmod=hashlib.sha512).hexdigest()

headers = {
    'Content-type' : 'application/json',
    'key' : api_key,
    'sign' : signature
}

r = requests.post(url, headers=headers, data=payload)
response = r.json()

print(response)
```

bit late I know, but I've been struggling with this for a while and hope this helps someone else.

**Comment by shacoof** [comment]
Thanks for that... working for me

**Comment by jnnnnn** [comment]
The trick here is that there can't be a space in the JSON body. So you have to specify a separator of `':'`. The default `': '` doesn't work.
If you use normal JSON encoding, the message gets rejected with HTTP 401.

**Comment by mastersneeza** [comment]
> > Any one willing to share a python 3 compatible version if they have it working... Not just snippets pretty please?
> 
> ```
> import os
> import sys
> import requests
> import pandas as pd
> import json
> from time import time
> import hmac
> import hashlib
> from itertools import count
> import urllib.parse
> 
> 
> api_key = 'yourapikeyhere'
> api_secret_key = b'yoursecretkeyhere'
> url = 'https://www.coinspot.com.au/api/ro/my/balances'
> 
> NONCE_COUNTER = count(int(time() * 1000))
> 
> payload = {
>     'nonce' : next(NONCE_COUNTER)
> }
> 
> payload = json.dumps(payload, separators=(',',':'))
> signature = hmac.new(api_secret_key, payload.encode('utf-8'), digestmod=hashlib.sha512).hexdigest()
> 
> headers = {
>     'Content-type' : 'application/json',
>     'key' : api_key,
>     'sign' : signature
> }
> 
> r = requests.post(url, headers=headers, data=payload)
> response = r.json()
> 
> print(response)
> ```
> 
> bit late I know, but I've been struggling with this for a while and hope this helps someone else.

man you are a legend Ive been spending a few hours trying to read JS documentation, the API documentation and more, only to find out i was using the wrong hashing method. Thank you!

**Comment by geekpete** [comment]
I have a separate branch where I'd had a crack at getting Python3 working:
https://github.com/geekpete/py-coinspot-api/tree/py3fixes

I'm yet to get back to it and make it the new master branch...
